window.baseUrl = 'http://localhost:3000/'
window.singInUrl = window.baseUrl + 'users/sign_in'
export const signUpUrl = window.baseUrl + 'users'
export const baseUrlUsers = window.baseUrl + 'users'
export const createAdvertUrl = window.baseUrl + 'adverts'
export const getAllCategories = window.baseUrl + 'all_categories'
export const getAllAdverts = window.baseUrl + 'adverts'
window.createCategoryUrl = window.baseUrl + 'categories'
window.singOutUrl = window.baseUrl + 'users/sign_out'
export const baseShowAdvert = window.baseUrl + 'adverts'

