window.baseUrl = 'http://localhost:3000/'
window.singInUrl = window.baseUrl + 'users/sign_in'
export const signUpUrl = window.baseUrl + 'users'
export const baseUrlUsers = window.baseUrl + 'users'
export const baseAdvertUrl = window.baseUrl + 'adverts'
export const getAllCategories = window.baseUrl + 'all_categories'
window.createCategoryUrl = window.baseUrl + 'categories'
