---
development:
  cloud_name: diw4a6aw6
  api_key: '142785226173178'
  api_secret: 3eIbT2zLvhhImtWeNA4hGjk5BLw
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: diw4a6aw6
  api_key: '142785226173178'
  api_secret: 3eIbT2zLvhhImtWeNA4hGjk5BLw
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: diw4a6aw6
  api_key: '142785226173178'
  api_secret: 3eIbT2zLvhhImtWeNA4hGjk5BLw
  enhance_image_tag: true
  static_file_support: false
