# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"
gem "rails", "~> 7.0.1"
gem "puma", "~> 5.0"

gem "devise", "~> 4.8", ">= 4.8.1"
gem "devise-jwt", "~> 0.9.0"
gem "fast_jsonapi"
gem "oj", "~> 3.3", ">= 3.3.5"
gem "pg", "1.3.0.rc3"
gem "rack-cors"
gem "rspec", "~> 3.5"
gem "rubocop", require: false
gem "rubocop-rails", "~> 2.13", ">= 2.13.2"
gem "rubocop-rails_config"
gem "uuid", "~> 2.3", ">= 2.3.9"
gem "rails-i18n", "~> 7.0", ">= 7.0.1"
gem "i18n", "~> 1.10"

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
end

group :development do
end
