# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

gem "devise", "~> 4.8", ">= 4.8.1"
gem "devise-jwt", "~> 0.9.0"
gem "fast_jsonapi"
gem "oj", "~> 3.3", ">= 3.3.5"
gem "pg", "1.3.0.rc3"
gem "rack-cors"
gem "cloudinary"
gem 'activestorage-validator'
gem "pundit"
gem 'active_model_serializers'
gem "uuid"
gem "rails-i18n", "~> 7.0", ">= 7.0.1"
gem "i18n", "~> 1.10"
gem 'will_paginate', '~> 3.3', '>= 3.3.1'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "dotenv-rails"
  gem 'rspec-rails', '~> 5.0', '>= 5.0.1'
  gem "rubocop", require: false
  gem "rubocop-rails", "~> 2.13", ">= 2.13.2"
  gem "rubocop-rails_config"
  gem 'simplecov', '~> 0.21.2'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
